######################################################################
# Automatically generated by qmake (2.01a) Wed May 25 23:23:58 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
OBJECTS_DIR = obj

# Input
HEADERS += FileHandler.hxx Tokenizer.hxx TagParser.hxx Log.hxx
SOURCES += FileHandler.cxx Tokenizer.cxx TagParser.cxx Log.cxx main.cxx 
